Repository ManageIQ/manageiq-smartstate, pull requests merged in 2018-05, with the labels that each got.

#63 Reduce Complexity in LinuxMount.rb
  lib/fs/modules/LinuxMount.rb
Labels: smart state, technical debt

#66 Fix to remove extra leading spaces in /etc/fstab during SSA
  lib/fs/modules/LinuxMount.rb
Labels: bug, fine/yes, smart state

#71 Reduce Complexity of Win32Software.rb
  lib/metadata/util/win32/Win32Software.rb
Labels: refactoring, smart state, technical debt

#69 Reduce Complexity of superblock.rb
  lib/fs/ext4/superblock.rb
Labels: smart state, technical debt

#73 Fix to remove duplicated records in services list after SSA
  lib/metadata/linux/LinuxSystemd.rb
Labels: bug, fine/yes, smart state

#68 Reduce Complexity of superblock.rb
  lib/fs/ext3/superblock.rb
Labels: smart state, technical debt

#74 Pre-existing Checkpoint Issue
  lib/disk/modules/VhdxDisk.rb
Labels: bug, fine/yes, smart state
