Repository ManageIQ/manageiq-smartstate, pull requests merged in 2020-10, with the labels that each got.

#141 [0.3] RHEV SSA Fails on VMs with Direct LUNs
  lib/MiqVm/MiqRhevmVm.rb
  lib/metadata/VmConfig/VmConfig.rb
Labels: bug

#137 add presence check to array wrap to handle to handle blank case
  lib/metadata/MIQExtract/MIQExtract.rb
Labels: bug

#142 Test with ruby 2.5.8 and 2.6.6
  .travis.yml
Labels: test

#143 Use manageiq-style
  .codeclimate.yml
  .rubocop.yml
  .rubocop_cc.yml
  manageiq-smartstate.gemspec
Labels: developer, enhancement

#146 Fix .rubocop_local.yml
  .rubocop_local.yml
Labels: developer
