Repository ManageIQ/manageiq-smartstate, pull requests merged in 2020-05, with the labels that each got.

#123 Fix Drive Letter Appending
  lib/metadata/util/md5deep.rb
Labels: bug, smart state

#124 Move miq_tempfile here
  lib/OpenStackExtract/MiqOpenStackVm/MiqOpenStackInstance.rb
  lib/miq_tempfile.rb
Labels: cleanup

#126 Fix README to point to travis-ci.com instead of travis-ci.org
  README.md
Labels: bug, developer

#127 Removing deprecated Gemnasium badge
  README.md
Labels: developer

#128 update azure armrest
  manageiq-smartstate.gemspec
Labels: dependencies, enhancement
