Repository ManageIQ/manageiq-smartstate, pull requests merged in 2020-02, with the labels that each got.

#102 Add install_time field to collection for Windows packages.
  lib/metadata/util/win32/Win32Software.rb
Labels: enhancement

#112 No need for MiqFaultTolerantVim without DRb
  lib/metadata/VmConfig/VmConfig.rb
Labels: technical debt

#111 Rescue TypeError During PEheader Processing
  lib/metadata/util/md5deep.rb
Labels: bug, smart state
