Repository ManageIQ/manageiq-smartstate, pull requests merged in 2021-01, with the labels that each got.

#149 Integrate miq-unicode.rb into smartstate
  lib/disk/modules/MSCommon.rb
  lib/disk/modules/VhdxDisk.rb
  lib/fs/fat32/directory_entry.rb
  lib/fs/iso9660/boot_sector.rb
  lib/fs/iso9660/directory_entry.rb
  lib/fs/iso9660/rock_ridge.rb
  lib/fs/ntfs/attrib_attribute_list.rb
  lib/fs/ntfs/attrib_file_name.rb
  lib/fs/ntfs/attrib_header.rb
  lib/fs/ntfs/attrib_index_root.rb
  lib/fs/ntfs/attrib_volume_name.rb
  lib/metadata/VmConfig/VmConfig.rb
  lib/metadata/linux/MiqRpmPackages.rb
  lib/metadata/util/win32/Win32EventLog.rb
  lib/metadata/util/win32/ms-registry.rb
  lib/metadata/util/win32/peheader.rb
  lib/miq_unicode.rb
  spec/miq_unicode_spec.rb
Labels: technical debt

#151 Update manageiq-style
  .codeclimate.yml
Labels: developer

#150 Remove MetakitFS and related files
  lib/fs/MetakitFS/MetakitFS.rb
  lib/fs/MetakitFS/test/Makefile
  lib/fs/MetakitFS/test/MkCollectFiles.rb
  lib/fs/MetakitFS/test/MkSelectFiles.rb
  lib/fs/MetakitFS/test/collect_files.yaml
  lib/fs/MetakitFS/test/init.rb
  lib/fs/MetakitFS/test/mk2vmdk.rb
  lib/fs/MetakitFS/test/mk4test.c
  lib/fs/MetakitFS/test/mkFsTest.rb
  lib/fs/MetakitFS/test/proto.rb
  lib/fs/MiqMountManager.rb
  lib/fs/VimDatastoreFS/VimDatastoreFS.rb
  lib/fs/test/copyTest.rb
  lib/fs/test/updateTest.rb
Labels: technical debt

#153 Remove gems-pending runcmd references in favor of AwesomeSpawn
  lib/VmLocalDiskAccess/test/localCfg.rb
  lib/metadata/VmConfig/GetNativeCfg.rb
  lib/metadata/VmConfig/xmlConfig.rb
  manageiq-smartstate.gemspec
Labels: technical debt

#154 dos2unix all the files
  lib/fs/fat32/directory_entry.rb
  spec/metadata/VmConfig/data/hyperv_utf_16.xml
  test/extract/data/test_vmware_config.vmx
  test/ts_extract.rb
  test/ts_metadata.rb
  test/vms.yml
Labels: cleanup
